---
- name: 'Instgitlab-ce Gitlab'
  hosts: 'gitlab-ce'
  gather_facts: true
  become: true

  roles:
    - role: 'alvistack.gitlab_ce'
      gitlab_package_modify_kernel_parameters: 'false'
      gitlab_release: '16.0'

