---
- name: 'Add the gitlab-runner repository'
  hosts: 'gitlab_runners'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.add_zypper_repository'
      repository_name: 'gitlab-runner'
      repository_baseurl: "https://download.opensuse.org/repositories/home:/ojkastl_buildservice:/gitlab-runner/{{ ansible_distribution_version }}/"
      auto_import_keys: '1'
      when:
        - ansible_distribution == "openSUSE Leap"
