---
- name: 'Install gitlab-runner'
  hosts: 'gitlab_runners'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.install_one_or_more_packages'
      packages_to_be_installed:
        - gitlab-runner
