---

- name: 'Run playbook-all_nodes-set_hostname.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-set_hostname.yml

- name: 'Run playbook-all_nodes-minimal_bashrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_bashrc.yml

- name: 'Run 10_SLES_register.yml'
  ansible.builtin.import_playbook: 10_SLES_register.yml

- name: 'Run playbook-all_nodes-zypper_ref_accept_keys.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-zypper_ref_accept_keys.yml
  when:
    - ansible_os_family == 'Suse'

- name: 'Run playbook-all_nodes-minimal_tmux_configuration.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml

- name: 'Run playbook-all_nodes-install_tmux.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_tmux.yml

- name: 'Run playbook-all_nodes-install_hostname.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_hostname.yml

# gitlab_runners only
- name: 'Run playbook-gitlab_runners-add_ojkastl_buildservice_gitlab-runners_repository.yml'
  ansible.builtin.import_playbook: playbook-gitlab_runners-add_ojkastl_buildservice_gitlab-runners_repository.yml

# gitlab_runners only
- name: 'Run playbook-gitlab_runners-install_gitlab-runner.yml'
  ansible.builtin.import_playbook: playbook-gitlab_runners-install_gitlab-runner.yml

- name: 'Run playbook-gitlab_server-copy_gitlab_RPM.yml'
  ansible.builtin.import_playbook: playbook-gitlab_server-copy_gitlab_RPM.yml

- name: 'Run playbook-gitlab_server-add_gitlab-ce_repository.yml'
  ansible.builtin.import_playbook: playbook-gitlab_server-add_gitlab-ce_repository.yml

- name: 'Run playbook-gitlab_server-alvistack.gitlab_ce.yml'
  ansible.builtin.import_playbook: playbook-gitlab_server-alvistack.gitlab_ce.yml
